[package]
name = "multi_mmap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
const-cstr = "0.3.0"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
